#!/bin/sh
# Scrolling text for MPD, adapted from:
#   https://github.com/jaagr/polybar/issues/353

if ! mpc >/dev/null 2>&1; then
  echo
  exit 1
elif mpc status | grep -q playing; then
  ( mpc current | zscroll -l 64 -d 0.3 ) &
else
  echo Not playing
fi
# Block until an event is emitted
mpc idle >/dev/null
